### ISSUE TITLE
Installation lab

### ISSUE THREAD

**Issue by llibman** [llibman/SEBC#1]

**Comment by llibman** [comment]
(waiting to be able to work with AWS)

**Comment by llibman** [comment]
Resolved access issue to Servian AWS account, commencing work

**Comment by llibman** [comment]
Created 5 RHEL instances:
54.206.92.109 cloudera1
54.252.154.13 cloudera2
54.252.148.59 cloudera3
54.252.151.43 cloudera4
54.206.127.74 cloudera5

**Comment by llibman** [comment]
Completed system configuration checks

**Comment by llibman** [comment]
Completed setting up database replication
(actually, turns out I had it all set up correctly last night, and spent two hours this morning debugging things at the raw port level using telnet, netstat etc, to finally figure out that the security configuration in AWS needed to be edited to allow access to port 3306 - AAARGHHHH!)

**Comment by llibman** [comment]
Completed installation of cluster using Cloudera Manager
(initial installation failed due to some ports being inaccessible, leaving scm in an unusable stage -> uninstalled and reinstalled scm, then on second installation, only installed on 4 of the 5 nodes due to the agent on the manager host failing with an "cm server guid updated" error; fixed by manually removing /var/lib/cloudera-scm-agent/cm_guid and then laboriously adding the host to the cluster and adding relevant instance roles for hive, hdfs and yarn on the node)

**Comment by mfernest** [comment]
Please marks finished labs with review. I'll close the Issue after evaluation.
