### ISSUE TITLE
Install CDH

### ISSUE THREAD

**Issue by llibman** [llibman/SEBC#10]

**Comment by llibman** [comment]
Wasted over an hour (including trying to upgrade, wipe and reinstall, etc three times) due to being unable to start the zookeeper service within the CDH installation wizard - turned out CM created the /var/lib/zookeeper directories with no permissions (d---------) and was fixed by manually removing and letting them be recreated

**Comment by llibman** [comment]
Still stuck; now zookeeper and HDFS are able to be started, but YARN fails to start DataNode, and there are no error messages in the stdout, stderr, or role log files

**Comment by llibman** [comment]
OK, same problem with YARN - "rm -r /var/lib/hadoop-yarn" on all hosts (and letting the directory be recreated) solved this again, the directory had "d---------" permissions

**Comment by llibman** [comment]
giving up (out of time; latest problem is that oozie cannot start)

**Comment by mfernest** [comment]
This is a peculiar show-stopper. I have to wonder if some stray umask value intervened here, as the problem was consistent across several attempts. 

Sometimes things just go wrong. It is evident from your lab submissions that you know how to do this work.
