### ISSUE TITLE
Security lab

### ISSUE THREAD

**Issue by llibman** [llibman/SEBC#6]
started two hours ago, forgot to open issue :)

**Comment by llibman** [comment]
completed setup of TLS 1 for communication between the CM manager and agents, as well as setup of https for the CM web UI itself
(following the instructions in https://www.cloudera.com/documentation/enterprise/latest/topics/how_to_configure_cm_tls.html,
with a certificate authority created using the instructions at https://jamielinux.com/docs/openssl-certificate-authority/index.htm and using it to sign the CSRs)

**Comment by llibman** [comment]
completed Kerberos integration with Cloudera Manager and the cluster Hadoop services
(setting up the Kerberos configuration and running the integration wizard was pretty straightforward; however after enabling Kerberos and restarting the cluster, all services bar ZooKeeper were red (bad health) - after some digging, turned out to be a problem with the 256-bit encryption not enabled -> installing the Java policy files solves the problem. Also the ticket renewer on Hue failed to start, which was eventually resolved through a "modprinc" command in kadmin; apparently the wizard created the relevant principal(s) before the kdc server was configured to issue renewable tickets.)

**Comment by llibman** [comment]
In progress with the Sentry lab; just managed to get beehive to work after it kept crashing with a "GSSException: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)"
With some blood, sweat, tears, and setting HADOOP_OPTS="-Dsun.security.krb5.debug=true", finally found out the problem was caused by the Kerberos tickets being caches in an OS-level KEYRING; fixed by changing /etc/krb5.conf and modifying the setting 'default_ccache_name' to be "FILE:/tmp/krb5cc_%{uid}".

**Comment by llibman** [comment]
Completed the Sentry lab

**Comment by mfernest** [comment]
Great job, all the way through.
